### ISSUE TITLE
Mostrar a coluna PARTICIPOU no grid de Inscricoes somente para eventos finalizados

### ISSUE THREAD

**Issue by rodrigorosa** [mateusnava/dia-de-treinamento#3]
Criar campo **data_evento:date** em **Evento**

**Comment by mateusnava** [comment]
Como vamos saber se um evento já foi finalizado? Hoje no modelo **Evento**, temos os seguintes campos:
* nome
* vagas

**Comment by rodrigorosa** [comment]
Cria um método finalizado e, por enquanto, retorna se data do evento
estiver no passado.
Futuramente, se tivermos outra forma mais rebuscada, podemos alterar
somente esse método.

**Comment by mateusnava** [comment]
Certo, problema é que não temos a data do evento, vamos criar esse atributo então.

**Comment by rodrigorosa** [comment]
Bãã! Não que seja importante saber a data do evento, né mano... chega lá e
um dia vai acontecer...

**Comment by mateusnava** [comment]
@rodrigorosa agora o atributo existe, podemos desenvolver essa feature.
